using UnityEditor;
using UnityEngine;
using System.Text;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using LitFramework.UI.Core.Window;


namespace LitFramework.UI.Core.Utility
{
    public static class UIAutoBindGenerator
    {
        public static void Generate(UIBase ui)
        {
            if (ui == null) return;

            var binds = ui.GetComponentsInChildren<UIBind>(true);

            // Hierarchy 顺序稳定排序（深度优先）
            var ordered = binds
                .OrderBy(b => GetHierarchyPath(b.transform))
                .ToArray();

            for (int i = 0; i < ordered.Length; i++)
            {
                Undo.RecordObject(ordered[i], "Assign UIBind Index");
                ordered[i].Editor_SetIndex(i);
                EditorUtility.SetDirty(ordered[i]);
            }

            GeneratePartial(ui, ordered);
        }

        static void GeneratePartial(UIBase ui, UIBind[] binds)
        {
            var type = ui.GetType();
            var ns = type.Namespace;
            var className = type.Name;

            var namespaces = new HashSet<string>
        {
            "UnityEngine"
        };

            // 收集命名空间
            foreach (var bind in binds)
            {
                var c = UIBindAutoResolver.Resolve(bind);
                if (c != null && !string.IsNullOrEmpty(c.GetType().Namespace))
                    namespaces.Add(c.GetType().Namespace);
            }

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb, ui);
            // using
            foreach (var use in namespaces)
                sb.AppendLine($"using {use};");

            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");

            // =====================
            // 字段声明
            // =====================
            for (int i = 0; i < binds.Length; i++)
            {
                var bind = binds[i];
                var comp = UIBindAutoResolver.Resolve(bind);
                if (comp == null) continue;

                var fieldName = MakeFieldName(comp, bind);
                var typeName = comp.GetType().Name;

                sb.AppendLine(
                    $"        private @{typeName} {fieldName};"
                );
            }

            sb.AppendLine();
            sb.AppendLine("        protected override void GetUI()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.GetUI();");

            // =====================
            // 赋值
            // =====================
            for (int i = 0; i < binds.Length; i++)
            {
                var bind = binds[i];
                var comp = UIBindAutoResolver.Resolve(bind);
                if (comp == null) continue;

                var fieldName = MakeFieldName(comp, bind);
                var typeName = comp.GetType().Name;

                sb.AppendLine(
                    $"            {fieldName} = GetBind<@{typeName}>({i});"
                );
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");

            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine("}");

            var dir = ui.GeneratedScriptPath;
            if (!IsValidGeneratePath(dir, out var error))
            {
                EditorUtility.DisplayDialog(
                    "UI AutoBind 生成失败",
                    error,
                    "OK"
                );
                return;
            }
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            var path = Path.Combine(dir, $"{className}.Bind.g.cs");
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            AssetDatabase.Refresh();
        }

        // =====================
        // 命名工具
        // =====================

        static string MakeFieldName(Component comp, UIBind bind)
        {
            // var typeName = comp.GetType().Name;
            var nodeName = MakeSafeFieldName(bind.name);

            // 使用 @ 提高区分度 & 安全性
            return $"b_{nodeName}";
        }

        static string MakeSafeFieldName(string name)
        {
            var sb = new StringBuilder(name.Length + 2);

            if (!char.IsLetter(name[0]) && name[0] != '_')
                sb.Append('_');

            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            return sb.ToString();
        }

        static string GetHierarchyPath(Transform t)
        {
            var parts = new List<string>();
            while (t != null)
            {
                parts.Add($"{t.GetSiblingIndex():000}_{t.name}");
                t = t.parent;
            }
            parts.Reverse();
            return string.Join("/", parts);
        }

        static bool IsValidGeneratePath(string path, out string error)
        {
            error = null;

            if (string.IsNullOrEmpty(path))
            {
                error = "生成路径为空";
                return false;
            }

            path = path.Replace("\\", "/");

            if (path.StartsWith("Assets/Packages") ||
                path.StartsWith("Assets/Library"))
            {
                error = "禁止生成到 Packages / Library 目录";
                return false;
            }

            return true;
        }
        static void AppendAutoGeneratedHeader(StringBuilder sb, UIBase ui)
        {
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <自动生成>");
            sb.AppendLine("//     本文件由 UIAutoBindGenerator 自动生成");
            sb.AppendLine("//     请勿手动修改此文件，重新生成将覆盖所有改动");
            sb.AppendLine("//");
            sb.AppendLine($"//     来源 UI : {ui.GetType().FullName}");
            sb.AppendLine($"//     生成时间 : {System.DateTime.Now:yyyy-MM-dd}");
            sb.AppendLine("// </自动生成>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
        }

    }
}